# Generated by Django 3.2 on 2021-05-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210419_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('plant_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.plant')),
            ],
        ),
    ]
