# Generated by Django 3.2 on 2021-06-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_reminder_base_tmstp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='intrvl_type',
            field=models.CharField(choices=[('S', 'SECONDS'), ('M', 'MINUTES'), ('H', 'HOURS'), ('D', 'DAYS'), ('W', 'WEEKS'), ('m', 'MONTHS'), ('Y', 'YEARS')], max_length=1),
        ),
    ]
