# Generated by Django 3.2 on 2021-06-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_reminder_intrvl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('D', 'DONE'), ('S', 'SKIPPED')], max_length=1)),
                ('log_tmstp', models.DateTimeField()),
                ('reminder_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.reminder')),
            ],
        ),
    ]
